package com.wuxin.tong.dao.entity;

import java.util.Date;

public class DajiInstantcallLimit {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daji_instantcall_limit.id
     *
     * @mbggenerated Tue Dec 04 16:27:15 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daji_instantcall_limit.interface_code
     *
     * @mbggenerated Tue Dec 04 16:27:15 CST 2018
     */
    private String interfaceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daji_instantcall_limit.app_key
     *
     * @mbggenerated Tue Dec 04 16:27:15 CST 2018
     */
    private String appKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daji_instantcall_limit.log_type
     *
     * @mbggenerated Tue Dec 04 16:27:15 CST 2018
     */
    private String logType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daji_instantcall_limit.top_limit
     *
     * @mbggenerated Tue Dec 04 16:27:15 CST 2018
     */
    private Double topLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daji_instantcall_limit.bottom_limit
     *
     * @mbggenerated Tue Dec 04 16:27:15 CST 2018
     */
    private Double bottomLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daji_instantcall_limit.statistic_time
     *
     * @mbggenerated Tue Dec 04 16:27:15 CST 2018
     */
    private Date statisticTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daji_instantcall_limit.id
     *
     * @return the value of daji_instantcall_limit.id
     *
     * @mbggenerated Tue Dec 04 16:27:15 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daji_instantcall_limit.id
     *
     * @param id the value for daji_instantcall_limit.id
     *
     * @mbggenerated Tue Dec 04 16:27:15 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daji_instantcall_limit.interface_code
     *
     * @return the value of daji_instantcall_limit.interface_code
     *
     * @mbggenerated Tue Dec 04 16:27:15 CST 2018
     */
    public String getInterfaceCode() {
        return interfaceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daji_instantcall_limit.interface_code
     *
     * @param interfaceCode the value for daji_instantcall_limit.interface_code
     *
     * @mbggenerated Tue Dec 04 16:27:15 CST 2018
     */
    public void setInterfaceCode(String interfaceCode) {
        this.interfaceCode = interfaceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daji_instantcall_limit.app_key
     *
     * @return the value of daji_instantcall_limit.app_key
     *
     * @mbggenerated Tue Dec 04 16:27:15 CST 2018
     */
    public String getAppKey() {
        return appKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daji_instantcall_limit.app_key
     *
     * @param appKey the value for daji_instantcall_limit.app_key
     *
     * @mbggenerated Tue Dec 04 16:27:15 CST 2018
     */
    public void setAppKey(String appKey) {
        this.appKey = appKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daji_instantcall_limit.log_type
     *
     * @return the value of daji_instantcall_limit.log_type
     *
     * @mbggenerated Tue Dec 04 16:27:15 CST 2018
     */
    public String getLogType() {
        return logType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daji_instantcall_limit.log_type
     *
     * @param logType the value for daji_instantcall_limit.log_type
     *
     * @mbggenerated Tue Dec 04 16:27:15 CST 2018
     */
    public void setLogType(String logType) {
        this.logType = logType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daji_instantcall_limit.top_limit
     *
     * @return the value of daji_instantcall_limit.top_limit
     *
     * @mbggenerated Tue Dec 04 16:27:15 CST 2018
     */
    public Double getTopLimit() {
        return topLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daji_instantcall_limit.top_limit
     *
     * @param topLimit the value for daji_instantcall_limit.top_limit
     *
     * @mbggenerated Tue Dec 04 16:27:15 CST 2018
     */
    public void setTopLimit(Double topLimit) {
        this.topLimit = topLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daji_instantcall_limit.bottom_limit
     *
     * @return the value of daji_instantcall_limit.bottom_limit
     *
     * @mbggenerated Tue Dec 04 16:27:15 CST 2018
     */
    public Double getBottomLimit() {
        return bottomLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daji_instantcall_limit.bottom_limit
     *
     * @param bottomLimit the value for daji_instantcall_limit.bottom_limit
     *
     * @mbggenerated Tue Dec 04 16:27:15 CST 2018
     */
    public void setBottomLimit(Double bottomLimit) {
        this.bottomLimit = bottomLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daji_instantcall_limit.statistic_time
     *
     * @return the value of daji_instantcall_limit.statistic_time
     *
     * @mbggenerated Tue Dec 04 16:27:15 CST 2018
     */
    public Date getStatisticTime() {
        return statisticTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daji_instantcall_limit.statistic_time
     *
     * @param statisticTime the value for daji_instantcall_limit.statistic_time
     *
     * @mbggenerated Tue Dec 04 16:27:15 CST 2018
     */
    public void setStatisticTime(Date statisticTime) {
        this.statisticTime = statisticTime;
    }
}