package com.wuxin.tong.dao.entity;

import java.util.Date;

public class TableStatisticStatus {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_statistic_status.id
     *
     * @mbggenerated Tue Nov 27 16:54:26 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_statistic_status.dept_name
     *
     * @mbggenerated Tue Nov 27 16:54:26 CST 2018
     */
    private String deptName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_statistic_status.table_name
     *
     * @mbggenerated Tue Nov 27 16:54:26 CST 2018
     */
    private String tableName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_statistic_status.type
     *
     * @mbggenerated Tue Nov 27 16:54:26 CST 2018
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_statistic_status.standard_code
     *
     * @mbggenerated Tue Nov 27 16:54:26 CST 2018
     */
    private String standardCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_statistic_status.is_need
     *
     * @mbggenerated Tue Nov 27 16:54:26 CST 2018
     */
    private String isNeed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_statistic_status.status
     *
     * @mbggenerated Tue Nov 27 16:54:26 CST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_statistic_status.statistic_date
     *
     * @mbggenerated Tue Nov 27 16:54:26 CST 2018
     */
    private Date statisticDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_statistic_status.id
     *
     * @return the value of table_statistic_status.id
     *
     * @mbggenerated Tue Nov 27 16:54:26 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_statistic_status.id
     *
     * @param id the value for table_statistic_status.id
     *
     * @mbggenerated Tue Nov 27 16:54:26 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_statistic_status.dept_name
     *
     * @return the value of table_statistic_status.dept_name
     *
     * @mbggenerated Tue Nov 27 16:54:26 CST 2018
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_statistic_status.dept_name
     *
     * @param deptName the value for table_statistic_status.dept_name
     *
     * @mbggenerated Tue Nov 27 16:54:26 CST 2018
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_statistic_status.table_name
     *
     * @return the value of table_statistic_status.table_name
     *
     * @mbggenerated Tue Nov 27 16:54:26 CST 2018
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_statistic_status.table_name
     *
     * @param tableName the value for table_statistic_status.table_name
     *
     * @mbggenerated Tue Nov 27 16:54:26 CST 2018
     */
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_statistic_status.type
     *
     * @return the value of table_statistic_status.type
     *
     * @mbggenerated Tue Nov 27 16:54:26 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_statistic_status.type
     *
     * @param type the value for table_statistic_status.type
     *
     * @mbggenerated Tue Nov 27 16:54:26 CST 2018
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_statistic_status.standard_code
     *
     * @return the value of table_statistic_status.standard_code
     *
     * @mbggenerated Tue Nov 27 16:54:26 CST 2018
     */
    public String getStandardCode() {
        return standardCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_statistic_status.standard_code
     *
     * @param standardCode the value for table_statistic_status.standard_code
     *
     * @mbggenerated Tue Nov 27 16:54:26 CST 2018
     */
    public void setStandardCode(String standardCode) {
        this.standardCode = standardCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_statistic_status.is_need
     *
     * @return the value of table_statistic_status.is_need
     *
     * @mbggenerated Tue Nov 27 16:54:26 CST 2018
     */
    public String getIsNeed() {
        return isNeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_statistic_status.is_need
     *
     * @param isNeed the value for table_statistic_status.is_need
     *
     * @mbggenerated Tue Nov 27 16:54:26 CST 2018
     */
    public void setIsNeed(String isNeed) {
        this.isNeed = isNeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_statistic_status.status
     *
     * @return the value of table_statistic_status.status
     *
     * @mbggenerated Tue Nov 27 16:54:26 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_statistic_status.status
     *
     * @param status the value for table_statistic_status.status
     *
     * @mbggenerated Tue Nov 27 16:54:26 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_statistic_status.statistic_date
     *
     * @return the value of table_statistic_status.statistic_date
     *
     * @mbggenerated Tue Nov 27 16:54:26 CST 2018
     */
    public Date getStatisticDate() {
        return statisticDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_statistic_status.statistic_date
     *
     * @param statisticDate the value for table_statistic_status.statistic_date
     *
     * @mbggenerated Tue Nov 27 16:54:26 CST 2018
     */
    public void setStatisticDate(Date statisticDate) {
        this.statisticDate = statisticDate;
    }
}