#端口
server:
  port: 8087

#数据库配置
spring:
  datasource:
     primary:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://192.168.40.14:3306/clean
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
     secondary:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://192.168.40.14:3306/daji
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: com/wuxin/tong/dao/xml/*/*.xml
  type-aliases-package: com.wuxin.tong.dao

#日志配置
logging:
  path: C:\Users\54192\Desktop\tly\log
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss SSS}] [%t] | %-5p | %C{1} | %m%n"
  file: C:\Users\54192\Desktop\tly\log\log.log

#hbase配置
hbase:
   zookeeper:
      quorum: namenode
      port: 2181

