#端口
server:
  port: 8087

#数据库配置
spring:
  datasource:
     primary:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/clean
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
     secondary:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost.14:3306/daji
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver

mybatis:
  primary:
       mapper-locations: classpath:com/wuxin/tong/dao/xml/primary/*.xml
       type-aliases-package: com.wuxin.tong.dao.mapper.primary
  secondary:
       apper-locations: classpath:com/wuxin/tong/dao/xml/secondary/*.xml
       type-aliases-package: com.wuxin.tong.dao.mapper.secondary


#日志配置
logging:
  path: C:\Users\54192\Desktop\tly\log
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss SSS}] [%t] | %-5p | %C{1} | %m%n"
  file: C:\Users\54192\Desktop\tly\log\log.log

#hbase配置
hbase:
   zookeeper:
      quorum: namenode
      port: 2181

