package com.wuxin.tong.dao.mapper.secondary;

import com.wuxin.tong.dao.entity.DajiInstantcallLimit;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface DajiInstantcallLimitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daji_instantcall_limit
     *
     * @mbggenerated Tue Dec 04 16:27:15 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daji_instantcall_limit
     *
     * @mbggenerated Tue Dec 04 16:27:15 CST 2018
     */
    int insert(DajiInstantcallLimit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daji_instantcall_limit
     *
     * @mbggenerated Tue Dec 04 16:27:15 CST 2018
     */
    int insertSelective(DajiInstantcallLimit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daji_instantcall_limit
     *
     * @mbggenerated Tue Dec 04 16:27:15 CST 2018
     */
    DajiInstantcallLimit selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daji_instantcall_limit
     *
     * @mbggenerated Tue Dec 04 16:27:15 CST 2018
     */
    int updateByPrimaryKeySelective(DajiInstantcallLimit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daji_instantcall_limit
     *
     * @mbggenerated Tue Dec 04 16:27:15 CST 2018
     */
    int updateByPrimaryKey(DajiInstantcallLimit record);
}